version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - celery
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    image: redis:latest
    ports:
      - 8080:6379
  celery:
    build:
      context: ./app
    command: celery -A config worker -l info
    volumes:
      - ./app/:/usr/src/app/
    environment:
      - DEBUG=1
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume:
  media_volume: