version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/media/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - celery
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./app/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  celery:
    build:
      context: ./app
    command: celery -A config worker -l info
    volumes:
      - ./app/:/usr/src/app/
    environment:
      - DEBUG=1
    env_file:
      - ./.env

volumes:
  postgres_data:
    external: true
  static_volume:
  media_volume: