# Generated by Django 4.1.4 on 2022-12-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('article', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=300)),
                ('vendor_code', models.CharField(blank=True, max_length=300, null=True)),
                ('article_provider', models.CharField(blank=True, max_length=300, null=True)),
                ('nomenclature_1c_code', models.IntegerField(blank=True, null=True)),
                ('last_barcode', models.IntegerField(blank=True, null=True)),
                ('url_product', models.URLField(blank=True, null=True)),
                ('purchase_price', models.PositiveIntegerField(blank=True, null=True)),
                ('current_price_before_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('new_price_before_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('price_after_dicount', models.PositiveIntegerField(blank=True, null=True)),
                ('current_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('recommended_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('agreed_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('cuurent_discount_promo', models.PositiveIntegerField(blank=True, null=True)),
                ('new_discount_promo', models.PositiveIntegerField(blank=True, null=True)),
                ('promotional_price', models.PositiveIntegerField(blank=True, null=True)),
                ('standart_price', models.PositiveIntegerField(blank=True, null=True)),
                ('max_price', models.PositiveIntegerField(blank=True, null=True)),
                ('min_price', models.PositiveIntegerField(blank=True, null=True)),
                ('rrc_price', models.PositiveIntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=300, null=True)),
                ('brand', models.CharField(blank=True, max_length=300, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('remainder', models.PositiveIntegerField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, max_length=300, null=True)),
                ('region', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('related_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('related_sub_categoy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
        ),
    ]
