# Generated by Django 4.1.4 on 2022-12-18 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_remove_strategylogicoperation_first_variable_and_more'),
        ('product', '0003_remove_competitor_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='strategy',
        ),
        migrations.CreateModel(
            name='StrategyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy')),
            ],
        ),
    ]
