# Generated by Django 4.1.4 on 2022-12-20 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_remove_strategy_journals_alter_strategy_logic_and_more'),
        ('product', '0004_remove_product_strategy_strategyproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('file_in', models.FileField(blank=True, null=True, upload_to='files/')),
                ('file_out', models.FileField(blank=True, null=True, upload_to='files/')),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='strategyproduct',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_strategy', to='strategy.strategy'),
        ),
    ]
