# Generated by Django 4.1.4 on 2022-12-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_product', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyElementVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('медианная цена конкурентов', 'медианная цена конкурентов'), ('мода цен конкурентов', 'мода цен конкурентов'), ('минимальная цена конкурентов', 'минимальная цена конкурентов'), ('средняя цена конкурентов', 'средняя цена конкурентов'), ('максимальная цена конкурентов', 'максимальная цена конкурентов')], max_length=300, null=True)),
                ('custom_variable', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyLogicOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(blank=True, choices=[('<', '<'), ('==', '=='), ('>', '>'), ('!=', '!='), ('<=', '<='), ('>=', '>=')], default='==', max_length=300, null=True)),
                ('first_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_logic_variable', to='strategy.strategyelementvariable')),
                ('second_variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_logic_variable', to='strategy.strategyelementvariable')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(blank=True, choices=[('+', '+'), ('=', '='), ('-', '-'), ('*', '*'), ('/', '/')], default='=', max_length=300, null=True)),
                ('custom_value', models.PositiveIntegerField(blank=True, null=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategyelemnt_strategy', to='strategy.strategy')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.strategyelementvariable')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyLogicOperationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('Истина', 'Истина'), ('Ложь', 'Ложь')], default='Истина', max_length=300, null=True)),
                ('after_result_logic_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_logic_operation', to='strategy.strategylogicoperation')),
                ('after_result_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.strategyoperation')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.strategylogicoperation')),
            ],
        ),
    ]
