# Generated by Django 4.1.4 on 2022-12-17 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='product',
        ),
        migrations.RemoveField(
            model_name='strategylogicoperationresult',
            name='operation',
        ),
        migrations.AddField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategyelementvariable',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.strategy'),
        ),
        migrations.AddField(
            model_name='strategylogicoperationresult',
            name='logical_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logical_result', to='strategy.strategylogicoperation'),
        ),
        migrations.AlterField(
            model_name='strategyelementvariable',
            name='title',
            field=models.CharField(blank=True, choices=[('медианная цена конкурентов', 'медианная цена конкурентов'), ('минимальная цена конкурентов', 'минимальная цена конкурентов'), ('средняя цена конкурентов', 'средняя цена конкурентов'), ('максимальная цена конкурентов', 'максимальная цена конкурентов')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='strategylogicoperation',
            name='operation',
            field=models.CharField(blank=True, choices=[('<', '<'), ('==', '=='), ('>', '>'), ('!=', '!='), ('<=', '<='), ('>=', '>=')], default='==', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='strategylogicoperationresult',
            name='result',
            field=models.CharField(blank=True, choices=[('Истина', 'Истина'), ('Ложь', 'Ложь')], default='Истина', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategyoperation_strategy', to='strategy.strategy'),
        ),
        migrations.AlterField(
            model_name='strategyoperation',
            name='variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_variable', to='strategy.strategyelementvariable'),
        ),
    ]
