# Generated by Django 4.1.4 on 2022-12-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_remove_strategy_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategylogicoperation',
            name='parent_logical_operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nested_logical_operation', to='strategy.strategylogicoperation'),
        ),
        migrations.AddField(
            model_name='strategylogicoperation',
            name='result',
            field=models.BooleanField(blank=True, choices=[(True, True), (False, False)], default=True, null=True),
        ),
        migrations.AddField(
            model_name='strategyoperation',
            name='logic_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_result', to='strategy.strategylogicoperation'),
        ),
        migrations.DeleteModel(
            name='StrategyLogicOperationResult',
        ),
    ]
