# Generated by Django 4.1.4 on 2022-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_strategylogicoperation_parent_logical_operation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategylogicoperation',
            name='first_variable',
        ),
        migrations.RemoveField(
            model_name='strategylogicoperation',
            name='parent_logical_operation',
        ),
        migrations.RemoveField(
            model_name='strategylogicoperation',
            name='second_variable',
        ),
        migrations.RemoveField(
            model_name='strategyoperation',
            name='logic_result',
        ),
        migrations.RemoveField(
            model_name='strategyoperation',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='strategyoperation',
            name='variable',
        ),
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='logic',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='StrategyElementVariable',
        ),
        migrations.DeleteModel(
            name='StrategyLogicOperation',
        ),
        migrations.DeleteModel(
            name='StrategyOperation',
        ),
    ]
