# Generated by Django 4.1.4 on 2022-12-20 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_strategy_journals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='journals',
        ),
        migrations.AlterField(
            model_name='strategy',
            name='logic',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='JournalStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journals', models.JSONField(blank=True, default=dict)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy')),
            ],
        ),
    ]
